trigger:
  branches:
    include:
    # triggers pushes to ALL branches
    - '*'
    # - main

pool: 
  vmImage: 'windows-latest'

name: $(Build.BuildId)

stages:
- template: templates/azure-pipeline-playwright-automation.yaml
  parameters:
    environment: 'main'
    runCommand: npx playwright test