name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install dotenv
      run: npm install dotenv --no-save
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run ESLint
      run: npx eslint .
    - name: Run Playwright tests tagged with @api
      # NOTE: This is a workaround for the issue with Playwright's --grep option.
      # For some reason, it doesn't work as expected in GitHub Actions.
      # Instead, we use the --project option to run tests in the 'api-tests
      # run: npx playwright test --grep="@api"
      run: npx playwright test --project=api-tests
    - name: Run Playwright tests in end-to-end.spec.ts file
      run: npx playwright test --project=end-to-end-tests
    - name: Run Playwright tests in fakerjs.spec.ts file
      run: npx playwright test --project=fakerjs-tests
    # - name: Run Playwright tests tagged with @smoke
      # NOTE: This is a workaround for the issue with Playwright's --grep option.
      # For some reason, it doesn't work as expected in GitHub Actions.
      # Instead, we use the --project option to run tests in the 'smoke-tests
      # run: npx playwright test --grep="@smoke"
    # run: npx playwright test --project=smoke-tests
    - name: Run all Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
